

[tool.poetry]
name = "clear-skies-aws"
version = "1.4.3"
description = "clearskies bindings for working in AWS"
authors = [
    "Conor Mancone <cmancone@gmail.com>",
    "tnijboer"
]
repository = "https://github.com/cmancone/clearskies-aws"
license = "MIT"
readme = "./README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
clear-skies = "^1.14.4"
boto3 = "^1.26.148"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
yapf = "^0.32.0"
boto3-stubs = "^1.26.148"

[tool.poetry.extras]
akeyless = ["akeyless-cloud-id", "akeyless"]
ses = ["jinja2"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
